# Generated by Django 3.1.4 on 2021-02-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201208_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.SlugField(max_length=160, unique=True),
        ),
    ]
